#!/usr/bin/env python3
"""
Master TRAITS MATRIX for Roll Call.

Canonical source of country facts: country_data.csv (generated by ingest.py from
raw_table.md). This module derives a large pool of candidate boolean criteria and
writes traits_matrix.csv (193 countries x every trait, Y/blank).

    python3 traits_matrix.py     # regenerates traits_matrix.csv + prints breadths

To add a trait: append one (key, group, label, predicate) to TRAITS and re-run.
To change country facts: edit country_data.csv (or raw_table.md + re-run ingest.py).
"""
import csv
import os

import build_criteria as B   # for NAMES, IDX, mask_of, popcount, letters, has_double

letters, has_double = B.letters, B.has_double
NAMES, IDX = B.NAMES, B.IDX
HERE = os.path.dirname(os.path.abspath(__file__))

# ---- load canonical data ---------------------------------------------------
def _load():
    d = {}
    with open(os.path.join(HERE, "country_data.csv")) as f:
        for r in csv.DictReader(f):
            nm = r["Country"]
            d[nm] = dict(
                capital=r["Capital"],
                pop=int(r["Population"]),
                area=int(r["Area_km2"]),
                continent=r["Continent"],
                subregion=r["Subregion"],
                landlocked=(r["Landlocked"] == "Yes"),
                neighbours=int(r["Bordering_countries"]),
                coasts=set() if r["Coasts"] == "none" else {x.strip() for x in r["Coasts"].split(";")},
                peak=int(r["Highest_peak_m"]),
                drives=r["Drives_on"],
                langs=[x.strip() for x in r["Official_languages"].split(";")],
                currency=r["Currency"],
                government=r["Government"],
                hemisphere=r["Hemisphere"],
                flag_colors={x.strip() for x in r["Flag_colors"].split(";")},
                flag_symbols=set() if r["Flag_symbols"] == "none" else {x.strip() for x in r["Flag_symbols"].split(";")},
                archipelago=(r["Archipelago"] == "Yes"),
                eu=(r["EU_member"] == "Yes"),
                commonwealth=(r["Commonwealth_member"] == "Yes"),
            )
    return d

D = _load()
def a(n): return D[n]
def L(n): return len(letters(n))
def caplet(n): return "".join(ch for ch in a(n)["capital"].lower() if ch.isalpha())

TRAITS = [
    # ================= NAME: letters =================
    ("nm_starts_vowel", "name-letters", "Name starts with a vowel",   lambda n: letters(n)[0] in "aeiou"),
    ("nm_ends_vowel",   "name-letters", "Name ends in a vowel",       lambda n: letters(n)[-1] in "aeiou"),
    ("nm_ends_cons",    "name-letters", "Name ends in a consonant",   lambda n: letters(n)[-1] not in "aeiou"),
    ("nm_ends_a",       "name-letters", "Name ends in A",             lambda n: letters(n).endswith("a")),
    ("nm_ends_n",       "name-letters", "Name ends in N",             lambda n: letters(n).endswith("n")),
    ("nm_ends_ia",      "name-letters", "Name ends in -IA",           lambda n: letters(n).endswith("ia")),
    ("nm_ends_land",    "name-letters", "Name ends in -LAND",         lambda n: letters(n).endswith("land")),
    ("nm_ends_stan",    "name-letters", "Name ends in -STAN",         lambda n: letters(n).endswith("stan")),
    ("nm_double",       "name-letters", "Name has a double letter",   has_double),
    ("nm_no_a",         "name-letters", "Name contains no A",         lambda n: "a" not in letters(n)),
    ("nm_no_e",         "name-letters", "Name contains no E",         lambda n: "e" not in letters(n)),
    ("nm_has_o",        "name-letters", "Name contains an O",         lambda n: "o" in letters(n)),
    ("nm_has_r",        "name-letters", "Name contains an R",         lambda n: "r" in letters(n)),
    ("nm_has_k",        "name-letters", "Name contains a K",          lambda n: "k" in letters(n)),
    ("nm_has_uncommon", "name-letters", "Name contains J, Q, X or Z", lambda n: any(c in letters(n) for c in "jqxz")),
    ("nm_first_last_same","name-letters","First and last letter the same", lambda n: letters(n)[0] == letters(n)[-1]),
    ("nm_starts_a_g",   "name-letters", "Name starts with A-G",       lambda n: letters(n)[0] <= "g"),
    ("nm_starts_h_m",   "name-letters", "Name starts with H-M",       lambda n: "h" <= letters(n)[0] <= "m"),
    ("nm_starts_n_z",   "name-letters", "Name starts with N-Z",       lambda n: letters(n)[0] >= "n"),
    ("nm_two_words",    "name-letters", "Name is more than one word",  lambda n: " " in n.strip()),
    # ================= NAME: length =================
    ("len_le5",  "name-length", "Name: 5 letters or fewer", lambda n: L(n) <= 5),
    ("len_le6",  "name-length", "Name: 6 letters or fewer", lambda n: L(n) <= 6),
    ("len_le7",  "name-length", "Name: 7 letters or fewer", lambda n: L(n) <= 7),
    ("len_6_7",  "name-length", "Name: 6 or 7 letters",     lambda n: 6 <= L(n) <= 7),
    ("len_7_8",  "name-length", "Name: 7 or 8 letters",     lambda n: 7 <= L(n) <= 8),
    ("len_8_9",  "name-length", "Name: 8 or 9 letters",     lambda n: 8 <= L(n) <= 9),
    ("len_ge8",  "name-length", "Name: 8 letters or more",  lambda n: L(n) >= 8),
    ("len_ge9",  "name-length", "Name: 9 letters or more",  lambda n: L(n) >= 9),
    ("len_ge10", "name-length", "Name: 10 letters or more", lambda n: L(n) >= 10),
    ("len_ge11", "name-length", "Name: 11 letters or more", lambda n: L(n) >= 11),
    # ================= LOCATION =================
    ("loc_africa",   "location", "In Africa",         lambda n: a(n)["continent"] == "Africa"),
    ("loc_asia",     "location", "In Asia",           lambda n: a(n)["continent"] == "Asia"),
    ("loc_europe",   "location", "In Europe",         lambda n: a(n)["continent"] == "Europe"),
    ("loc_na",       "location", "In North America",  lambda n: a(n)["continent"] == "North America"),
    ("loc_sa",       "location", "In South America",  lambda n: a(n)["continent"] == "South America"),
    ("loc_americas", "location", "In the Americas",   lambda n: a(n)["continent"] in ("North America", "South America")),
    ("loc_oceania",  "location", "In Oceania",        lambda n: a(n)["continent"] == "Oceania"),
    ("loc_north",    "location", "Northern hemisphere",        lambda n: a(n)["hemisphere"] == "Northern"),
    ("loc_south",    "location", "Southern hemisphere",        lambda n: a(n)["hemisphere"] == "Southern"),
    ("loc_equator",  "location", "Equator passes through it",  lambda n: a(n)["hemisphere"] == "Both"),
    # ---- subregions (each only counts when reasonably broad; see breadths) ----
    ("sr_caribbean","location", "In the Caribbean",   lambda n: a(n)["subregion"] == "Caribbean"),
    ("sr_camerica", "location", "In Central America",  lambda n: a(n)["subregion"] == "Central America"),
    ("sr_mideast",  "location", "In the Middle East",  lambda n: a(n)["subregion"] == "Middle East"),
    ("sr_wafrica",  "location", "In West Africa",      lambda n: a(n)["subregion"] == "West Africa"),
    ("sr_eafrica",  "location", "In East Africa",      lambda n: a(n)["subregion"] == "East Africa"),
    ("sr_safrica",  "location", "In Southern Africa",  lambda n: a(n)["subregion"] == "Southern Africa"),
    ("sr_seasia",   "location", "In Southeast Asia",   lambda n: a(n)["subregion"] == "Southeast Asia"),
    ("sr_sasia",    "location", "In South Asia",       lambda n: a(n)["subregion"] == "South Asia"),
    ("sr_casia",    "location", "In Central Asia",     lambda n: a(n)["subregion"] == "Central Asia"),
    ("sr_balkans",  "location", "In the Balkans",      lambda n: a(n)["subregion"] == "Balkans"),
    ("sr_nordic",   "location", "Nordic country",      lambda n: a(n)["subregion"] == "Nordic"),
    ("sr_weurope",  "location", "In Western Europe",   lambda n: a(n)["subregion"] == "Western Europe"),
    ("sr_ceurope",  "location", "In Central Europe",   lambda n: a(n)["subregion"] == "Central Europe"),
    # ================= BORDERS / SHAPE =================
    ("b_landlocked", "borders", "Landlocked",                 lambda n: a(n)["landlocked"]),
    ("b_coastal",    "borders", "Has a sea coastline",        lambda n: not a(n)["landlocked"]),
    ("b_island",     "borders", "Island (no land borders)",   lambda n: a(n)["neighbours"] == 0),
    ("b_archipelago","borders", "Archipelago (many islands)", lambda n: a(n)["archipelago"]),
    ("b_one",        "borders", "Borders exactly one country", lambda n: a(n)["neighbours"] == 1),
    ("b_le2",        "borders", "Borders 1 or 2 countries",    lambda n: 1 <= a(n)["neighbours"] <= 2),
    ("b_mid",        "borders", "Borders 2 to 4 countries",    lambda n: 2 <= a(n)["neighbours"] <= 4),
    ("b_ge3",        "borders", "Borders 3 or more countries", lambda n: a(n)["neighbours"] >= 3),
    ("b_ge4",        "borders", "Borders 4 or more countries", lambda n: a(n)["neighbours"] >= 4),
    ("b_ge5",        "borders", "Borders 5 or more countries", lambda n: a(n)["neighbours"] >= 5),
    # ================= COASTS =================
    ("c_atlantic", "coasts", "Has an Atlantic coast",      lambda n: "Atlantic" in a(n)["coasts"]),
    ("c_pacific",  "coasts", "Has a Pacific coast",        lambda n: "Pacific" in a(n)["coasts"]),
    ("c_indian",   "coasts", "Has an Indian Ocean coast",  lambda n: "Indian" in a(n)["coasts"]),
    ("c_med",      "coasts", "Has a Mediterranean coast",  lambda n: "Mediterranean" in a(n)["coasts"]),
    ("c_arctic",   "coasts", "Has an Arctic coast",        lambda n: "Arctic" in a(n)["coasts"]),
    ("c_multi",    "coasts", "Touches two or more seas",   lambda n: len(a(n)["coasts"]) >= 2),
    # ================= PHYSICAL (elevation) =================
    ("p_ge2000", "physical", "Has a peak above 2,000 m", lambda n: a(n)["peak"] >= 2000),
    ("p_ge3000", "physical", "Has a peak above 3,000 m", lambda n: a(n)["peak"] >= 3000),
    ("p_ge4000", "physical", "Has a peak above 4,000 m", lambda n: a(n)["peak"] >= 4000),
    ("p_ge5000", "physical", "Has a peak above 5,000 m", lambda n: a(n)["peak"] >= 5000),
    ("p_flat",   "physical", "Highest point under 1,000 m", lambda n: a(n)["peak"] < 1000),
    # ================= SIZE (area) =================
    ("a_ge1m",   "area", "Area over 1 million km2",  lambda n: a(n)["area"] >= 1_000_000),
    ("a_lt50k",  "area", "Area under 50,000 km2",    lambda n: a(n)["area"] < 50_000),
    ("a_lt20k",  "area", "Area under 20,000 km2",    lambda n: a(n)["area"] < 20_000),
    # ================= POPULATION =================
    ("pop_ge100m", "population", "Population over 100 million", lambda n: a(n)["pop"] >= 100_000_000),
    ("pop_ge50m",  "population", "Population over 50 million",  lambda n: a(n)["pop"] >= 50_000_000),
    ("pop_ge20m",  "population", "Population over 20 million",  lambda n: a(n)["pop"] >= 20_000_000),
    ("pop_lt5m",   "population", "Population under 5 million",  lambda n: a(n)["pop"] < 5_000_000),
    ("pop_lt1m",   "population", "Population under 1 million",  lambda n: a(n)["pop"] < 1_000_000),
    # ================= FLAG: colours =================
    ("fc_red",    "flag-colors", "Flag has red",    lambda n: "red" in a(n)["flag_colors"]),
    ("fc_blue",   "flag-colors", "Flag has blue",   lambda n: "blue" in a(n)["flag_colors"]),
    ("fc_green",  "flag-colors", "Flag has green",  lambda n: "green" in a(n)["flag_colors"]),
    ("fc_yellow", "flag-colors", "Flag has yellow", lambda n: "yellow" in a(n)["flag_colors"]),
    ("fc_white",  "flag-colors", "Flag has white",  lambda n: "white" in a(n)["flag_colors"]),
    ("fc_black",  "flag-colors", "Flag has black",  lambda n: "black" in a(n)["flag_colors"]),
    ("fc_orange", "flag-colors", "Flag has orange", lambda n: "orange" in a(n)["flag_colors"]),
    ("fc_3plus",  "flag-colors", "Flag has 3+ colours", lambda n: len(a(n)["flag_colors"]) >= 3),
    ("fc_4plus",  "flag-colors", "Flag has 4+ colours", lambda n: len(a(n)["flag_colors"]) >= 4),
    # ================= FLAG: symbols =================
    ("fs_star",     "flag-symbols", "Flag has a star",        lambda n: "star" in a(n)["flag_symbols"]),
    ("fs_crescent", "flag-symbols", "Flag has a crescent",    lambda n: "crescent" in a(n)["flag_symbols"]),
    ("fs_cross",    "flag-symbols", "Flag has a cross",       lambda n: "cross" in a(n)["flag_symbols"]),
    ("fs_sun",      "flag-symbols", "Flag has a sun or disc", lambda n: "sun/disc" in a(n)["flag_symbols"]),
    ("fs_emblem",   "flag-symbols", "Flag has a coat of arms/emblem", lambda n: "coat of arms/emblem" in a(n)["flag_symbols"]),
    ("fs_animal",   "flag-symbols", "Flag has an animal",     lambda n: "animal" in a(n)["flag_symbols"]),
    ("fs_plant",    "flag-symbols", "Flag has a plant",       lambda n: "plant" in a(n)["flag_symbols"]),
    ("fs_any",      "flag-symbols", "Flag has any symbol",    lambda n: len(a(n)["flag_symbols"]) >= 1),
    ("fs_none",     "flag-symbols", "Flag is colours only (no symbol)", lambda n: len(a(n)["flag_symbols"]) == 0),
    # ================= POLITICS / CULTURE =================
    ("g_monarchy",  "politics", "Is a monarchy",        lambda n: "monarchy" in a(n)["government"].lower()),
    ("g_republic",  "politics", "Is a republic",        lambda n: a(n)["government"] == "Republic"),
    ("g_drives_left","politics","Drives on the left",   lambda n: a(n)["drives"] == "Left"),
    ("g_eu",        "politics", "EU member",            lambda n: a(n)["eu"]),
    ("g_commonwealth","politics","Commonwealth member", lambda n: a(n)["commonwealth"]),
    # ================= LANGUAGE =================
    ("l_english","language", "English is official",     lambda n: "English" in a(n)["langs"]),
    ("l_french", "language", "French is official",      lambda n: "French" in a(n)["langs"]),
    ("l_spanish","language", "Spanish is official",     lambda n: "Spanish" in a(n)["langs"]),
    ("l_arabic", "language", "Arabic is official",      lambda n: "Arabic" in a(n)["langs"]),
    ("l_portuguese","language","Portuguese is official",lambda n: "Portuguese" in a(n)["langs"]),
    ("l_multi",  "language", "Two or more official languages", lambda n: len(a(n)["langs"]) >= 2),
    # ================= CURRENCY =================
    ("cur_dollar","currency", "Currency is a dollar", lambda n: a(n)["currency"] == "Dollar"),
    ("cur_euro",  "currency", "Uses the euro",        lambda n: a(n)["currency"] == "Euro"),
    ("cur_franc", "currency", "Currency is a franc",  lambda n: a(n)["currency"] == "Franc"),
    ("cur_pound", "currency", "Currency is a pound",  lambda n: a(n)["currency"] == "Pound"),
    ("cur_peso",  "currency", "Currency is a peso",   lambda n: a(n)["currency"] == "Peso"),
    ("cur_dinar", "currency", "Currency is a dinar",  lambda n: a(n)["currency"] == "Dinar"),
    # ================= CAPITAL =================
    ("cap_starts_vowel","capital","Capital starts with a vowel", lambda n: caplet(n)[:1] in set("aeiou")),
    ("cap_le5",         "capital","Capital: 5 letters or fewer", lambda n: 0 < len(caplet(n)) <= 5),
    ("cap_ge9",         "capital","Capital: 9 letters or more",  lambda n: len(caplet(n)) >= 9),
    ("cap_two_words",   "capital","Capital is more than one word",lambda n: " " in a(n)["capital"].strip()),
    ("cap_shares_name", "capital","Capital shares the country's name", lambda n: n.split()[0].lower() in a(n)["capital"].lower()),
    ("cap_same_initial","capital","Capital shares country's first letter", lambda n: caplet(n)[:1] == letters(n)[:1]),
]


def trait_masks():
    """{key: (group, label, bitmask)} for exploration scripts."""
    return {k: (g, lbl, B.mask_of(p)) for (k, g, lbl, p) in TRAITS}


def main():
    path = os.path.join(HERE, "traits_matrix.csv")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Country", "Continent", "Subregion", "Population", "Area_km2",
                    "Landlocked", "Neighbours", "Peak_m"]
                   + [f"[{g}] {lbl}" for (_, g, lbl, _) in TRAITS])
        for nm in NAMES:
            at = a(nm)
            base = [nm, at["continent"], at["subregion"], at["pop"], at["area"],
                    at["landlocked"], at["neighbours"], at["peak"]]
            w.writerow(base + ["Y" if p(nm) else "" for (_, _, _, p) in TRAITS])
    print(f"Wrote {path}  ({len(NAMES)} countries x {len(TRAITS)} traits)\n")
    print("Trait breadths (count / 193); * = outside the ~8%-45% sweet spot:")
    grp = None
    for k, g, lbl, p in TRAITS:
        if g != grp:
            grp = g
            print(f"  -- {g} --")
        c = sum(1 for n in NAMES if p(n))
        flag = "" if 15 <= c <= 87 else " *"
        print(f"     {lbl:38s} {c:3d} ({c/len(NAMES)*100:2.0f}%){flag}")


if __name__ == "__main__":
    main()
